apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: retail-store
type: Opaque
data:
  # Base64 encoded password: "retailstore123"
  db-password: cmV0YWlsc3RvcmUxMjM=
  # Base64 encoded username: "catalog_user"
  catalog-username: Y2F0YWxvZ191c2Vy
  # Base64 encoded username: "orders_user"  
  orders-username: b3JkZXJzX3VzZXI=
  # Base64 encoded username: "rabbitmq"
  rabbitmq-username: cmFiYml0bXE=
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: retail-store
type: Opaque
data:
  # Base64 encoded: "key"
  aws-access-key-id: a2V5
  # Base64 encoded: "dummy"
  aws-secret-access-key: ZHVtbXk=
