apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: retail-store
data:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: "mysql"
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: "catalog-db:3306"
  GIN_MODE: "release"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: retail-store
data:
  RETAIL_CART_PERSISTENCE_PROVIDER: "dynamodb"
  RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT: "http://carts-db:8000"
  RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
  namespace: retail-store
data:
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: "redis"
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: "redis://checkout-redis:6379"
  RETAIL_CHECKOUT_ENDPOINTS_ORDERS: "http://orders:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: retail-store
data:
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: "postgres"
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: "orders-db:5432"
  RETAIL_ORDERS_PERSISTENCE_NAME: "orders"
  RETAIL_ORDERS_MESSAGING_PROVIDER: "rabbitmq"
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: "rabbitmq:5672"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: retail-store
data:
  RETAIL_UI_ENDPOINTS_CATALOG: "http://catalog:8080"
  RETAIL_UI_ENDPOINTS_CARTS: "http://carts:8080"
  RETAIL_UI_ENDPOINTS_ORDERS: "http://orders:8080"
  RETAIL_UI_ENDPOINTS_CHECKOUT: "http://checkout:8080"
