apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retail-store
  labels:
    app: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: public.ecr.aws/aws-containers/retail-store-sample-orders:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
          value: "true"
        - name: RETAIL_ORDERS_PERSISTENCE_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: RETAIL_ORDERS_PERSISTENCE_PROVIDER
        - name: RETAIL_ORDERS_PERSISTENCE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: RETAIL_ORDERS_PERSISTENCE_ENDPOINT
        - name: RETAIL_ORDERS_PERSISTENCE_NAME
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: RETAIL_ORDERS_PERSISTENCE_NAME
        - name: RETAIL_ORDERS_PERSISTENCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: orders-username
        - name: RETAIL_ORDERS_PERSISTENCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        - name: RETAIL_ORDERS_MESSAGING_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: RETAIL_ORDERS_MESSAGING_PROVIDER
        - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES
          valueFrom:
            configMapKeyRef:
              name: orders-config
              key: RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES
        - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: rabbitmq-username
        - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: retail-store
spec:
  selector:
    app: orders
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
